### ISSUE TITLE
pointer dla checkbox-a

### ISSUE THREAD

**Issue by bogolubow** [daankh/Sit-on-chair#2]
W przy zaznaczaniu checkbox-a warto pomyśleć o `cursor: pointer` jak i innych elementach klikalnych

**Comment by daankh** [comment]
Ustawiłem pointer na checkboxie. Jak patrzę to mam cursor: pointer na wszystkich buttonach i linkach, oraz na strzałkach do slidera, więc mógłbyś przybliżyć, o jakie elemeny jeszcze chodzi, bo nie bardzo wiem?
