### ISSUE TITLE
nazewnictwo klas w BEM

### ISSUE THREAD

**Issue by bogolubow** [daankh/Sit-on-chair#3]
Czasami mam wrażenie, że troszkę nazewnictwo kuleje.

np. `product-card--info` powinno być `product-card product-card--info`, czyli masz podstawowe style, a modyfikator dodaje "swoje".

Dobieranie samej nazwy również bym troszkę zmodyfikował tj. np. zamiast `header__nav-list-item`, blokiem nazwałbym `main-nav`, a elementem np `item`, trochę krócej to potem ułatwia utworzyć modyfikator np. `main-nav--dropdown`.

**Comment by daankh** [comment]
Notacja BEM poprawiona. Myślę, że teraz powinno być OK.
