### ISSUE TITLE
px, rem

### ISSUE THREAD

**Issue by bogolubow** [daankh/Sit-on-chair#5]
Może warto zastanowić się czy chcesz mieszać px i rem-y. Oczywiście to zalęzy od zamysłu, ale np. przy zmianie fontu dla `.card-price-value` nie chcesz też zwiększyć rozmiaru tego okręgu? Może warto zastosować dla tego rozmiaru również rem, aby po zmianie wielkości fontu bazowego ten element również się powiększył :)

**Comment by daankh** [comment]
Pozmieniałem px na remy tam gdzie wydawało mi się to zasadne. Teraz wydaje się, że strona lepiej adaptuje się do zmiany wielkości fontu bazowego, chociaż bez media queries by się nie obyło.
